### ISSUE TITLE
Milestone 1 Feedback

### ISSUE THREAD

**Issue by tonyliang19** [sgskung/dsci-310-group-11#11]
Please read below feedbacks on things that you could've improve on for future milestones, **NOTE** if these are not fixed, marks will be deducted. If you have any questions on these feedbacks, please feel free to drop-in to my office hour or during lecture time

# Milestone 1 Feedback Group 11 

### README.md

- [x] #20

### Project File and Directory Structure

- [x] #21
- [x] Extra `analysis.ipynb`, you should get rid of this after having `<xxxx>_analysis.ipynb`, as existence of both files could confuse readers **-1**

#### Workflow

- [x] #16

#### Project/Milestones/Issues

- [x] #15

- [x] #14

#### Flow Version Control

- [x] #13

### Reproducibility

- [x] Failed to reproduce the analysis from the documentation provided in README.md **-10**
- [x] Not reproducible environment (by poor Dockerfile definition) **-5**
- [x] #12

**Comment by tonyliang19** [comment]
Why is this closed now, when you still have two boxes unchecked? Just curious though

**Comment by sgskung** [comment]
SORRY I forgot to click the boxes before closing the issue haha.
1. The report is runnable now through the Docker instructions that produce the html that can be viewed.
2. I assumed reproducible environment meant the same as the first point, but does this mean runnable in jupyter lab? Should I alter the instructions to include that environment?

**Comment by tonyliang19** [comment]
> SORRY I forgot to click the boxes before closing the issue haha.
> 
> 1. The report is runnable now through the Docker instructions that produce the html that can be viewed.
> 2. I assumed reproducible environment meant the same as the first point, but does this mean runnable in jupyter lab? Should I alter the instructions to include that environment?

Yes, your environment must be runnable of either in Rstudio or Jupyter lab

**Comment by sgskung** [comment]
Ok @AnthonyH504 @chrisp-6, re-opening this issue to fix the last bullet point. Apologies for the confusion.

**Comment by sgskung** [comment]
Dockerfile updated in branch named jupyer-env - reproducible on mac/linux machines through dockerfile definition
Moved windows reproducibility to Milestone 2 revisions.
