### ISSUE TITLE
Milestone 3 Feedback

### ISSUE THREAD

**Issue by tonyliang19** [sgskung/dsci-310-group-11#57]
# Milestone 3 Feedback Group 11

## Report written in literate code document code, which primarily functions to source analysis artifacts and format document

- [ ] Did not completely modify jupyter notebook to literate code document, which you should directly source/read intermidiate/final results generated from your scripts **-5**

## Data anaylysis pipeline in GNU Make exists and works to run analysis from beginning to end, as well as to clean up the analysis 

- [x] Failed to run all, stuck at one target specifically due to chrome executable issue **-10**

## Analysis can be run reproducibly using documentation provided in README

- [x] failed to reproduce, but still see effort there **-5**

## Address Feedback from Milestone 1 and 2

Up to 50 % of Milestone 1 + Milestone 2 points, if feedback and comments are adequately addressed

### [Milestone 2 Feedback](https://github.com/sgskung/dsci-310-group-11/issues/29)

- Functions are well documented and Test **50% of 4 = 2**
- Analysis can be run reproducibly using README **50% of 11 = 5.5**

Total = $2 + 5.5 = 7.5$ points 

Dont worry about the `Tests` section and please leave the feedback issues (Milestone 1, 2, 3) open

### [Milestone 1 Feedback](https://github.com/sgskung/dsci-310-group-11/issues/11)

You fixed all feedbacks, which is **50% of 33 = 16.5** partial marks added to your Milestone 1 grade.
